# Generated by Django 5.2.10 on 2026-01-16 19:49

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('widget_name', models.CharField(max_length=100, verbose_name='اسم العنصر')),
                ('widget_type', models.CharField(choices=[('chart', 'رسم بياني'), ('metric', 'مقياس'), ('table', 'جدول'), ('list', 'قائمة'), ('map', 'خريطة')], default='metric', max_length=50, verbose_name='نوع العنصر')),
                ('data_source', models.CharField(choices=[('daily_stats', 'الإحصائيات اليومية'), ('performance_metrics', 'مقاييس الأداء'), ('reports', 'البلاغات'), ('users', 'المستخدمين'), ('matches', 'المطابقات'), ('custom_query', 'استعلام مخصص')], default='daily_stats', max_length=50, verbose_name='مصدر البيانات')),
                ('query', models.TextField(blank=True, verbose_name='الاستعلام')),
                ('filters', models.JSONField(blank=True, null=True, verbose_name='الفلاتر')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('size', models.CharField(choices=[('small', 'صغير (1x1)'), ('medium', 'متوسط (2x1)'), ('large', 'كبير (2x2)'), ('full', 'كامل (3x2)')], default='medium', max_length=20, verbose_name='الحجم')),
                ('column', models.IntegerField(default=1, verbose_name='العمود')),
                ('row', models.IntegerField(default=1, verbose_name='الصف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('refresh_interval', models.IntegerField(default=300, help_text='0 = لا يتم التحديث تلقائياً', verbose_name='فترة التحديث (ثواني)')),
                ('allowed_roles', models.JSONField(default=list, help_text='قائمة الأدوار التي يمكنها رؤية هذا العنصر', verbose_name='الأدوار المسموحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عنصر لوحة تحكم',
                'verbose_name_plural': 'عناصر لوحة التحكم',
                'ordering': ['column', 'row', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metric_name', models.CharField(max_length=100, unique=True, verbose_name='اسم المقياس')),
                ('metric_description', models.TextField(blank=True, verbose_name='وصف المقياس')),
                ('current_value', models.FloatField(default=0.0, verbose_name='القيمة الحالية')),
                ('target_value', models.FloatField(default=100.0, verbose_name='القيمة المستهدفة')),
                ('min_value', models.FloatField(default=0.0, verbose_name='القيمة الدنيا')),
                ('max_value', models.FloatField(default=100.0, verbose_name='القيمة القصوى')),
                ('unit', models.CharField(default='%', max_length=50, verbose_name='الوحدة')),
                ('category', models.CharField(choices=[('system', 'نظام'), ('matching', 'مطابقة'), ('user', 'مستخدم'), ('report', 'بلاغ'), ('security', 'أمان')], default='system', max_length=50, verbose_name='الفئة')),
                ('direction', models.CharField(choices=[('higher_better', 'الأعلى أفضل'), ('lower_better', 'الأقل أفضل'), ('target', 'الهدف أفضل')], default='higher_better', max_length=20, verbose_name='الاتجاه')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('update_frequency', models.CharField(choices=[('realtime', 'حقيقي'), ('hourly', 'كل ساعة'), ('daily', 'يومي'), ('weekly', 'أسبوعي')], default='daily', max_length=20, verbose_name='تكرار التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('threshold_warning', models.FloatField(default=70.0, verbose_name='عتبة التحذير')),
                ('threshold_critical', models.FloatField(default=50.0, verbose_name='عتبة الخطير')),
            ],
            options={
                'verbose_name': 'مقياس أداء',
                'verbose_name_plural': 'مقاييس الأداء',
                'ordering': ['category', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(choices=[('performance', 'أداء'), ('user', 'مستخدمين'), ('reports', 'بلاغات'), ('matching', 'مطابقة'), ('financial', 'مالي'), ('custom', 'مخصص')], default='performance', max_length=50, verbose_name='نوع التقرير')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('filters', models.JSONField(blank=True, null=True, verbose_name='الفلاتر')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='البيانات')),
                ('charts', models.JSONField(blank=True, null=True, verbose_name='الرسوم البيانية')),
                ('insights', models.TextField(blank=True, verbose_name='الرؤى والتحليلات')),
                ('recommendations', models.TextField(blank=True, verbose_name='التوصيات')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='مجدول')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='تكرار الجدولة')),
                ('export_formats', models.JSONField(default=list, help_text='قائمة الصيغ المدعومة: [pdf, excel, csv, json]', verbose_name='صيغ التصدير')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل التالي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('generating', 'قيد التوليد'), ('ready', 'جاهز'), ('failed', 'فشل'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='المستخدمون الذين يمكنهم رؤية هذا التقرير', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون المسموح لهم')),
            ],
            options={
                'verbose_name': 'تقرير تحليلي',
                'verbose_name_plural': 'التقارير التحليلية',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='التاريخ')),
                ('total_users', models.IntegerField(default=0, verbose_name='إجمالي المستخدمين')),
                ('new_users', models.IntegerField(default=0, verbose_name='مستخدمين جدد')),
                ('active_users', models.IntegerField(default=0, verbose_name='مستخدمين نشطين')),
                ('verified_users', models.IntegerField(default=0, verbose_name='مستخدمين موثوقين')),
                ('total_reports', models.IntegerField(default=0, verbose_name='إجمالي البلاغات')),
                ('new_reports', models.IntegerField(default=0, verbose_name='بلاغات جديدة')),
                ('missing_reports', models.IntegerField(default=0, verbose_name='بلاغات مفقودين')),
                ('found_reports', models.IntegerField(default=0, verbose_name='بلاغات معثور عليهم')),
                ('resolved_reports', models.IntegerField(default=0, verbose_name='بلاغات محلولة')),
                ('pending_review_reports', models.IntegerField(default=0, verbose_name='بلاغات قيد المراجعة')),
                ('total_matches', models.IntegerField(default=0, verbose_name='إجمالي المطابقات')),
                ('new_matches', models.IntegerField(default=0, verbose_name='مطابقات جديدة')),
                ('accepted_matches', models.IntegerField(default=0, verbose_name='مطابقات مقبولة')),
                ('false_positive_matches', models.IntegerField(default=0, verbose_name='مطابقات إيجابية خاطئة')),
                ('match_success_rate', models.FloatField(default=0.0, verbose_name='معدل نجاح المطابقة')),
                ('total_logins', models.IntegerField(default=0, verbose_name='إجمالي عمليات الدخول')),
                ('total_searches', models.IntegerField(default=0, verbose_name='إجمالي عمليات البحث')),
                ('total_notifications', models.IntegerField(default=0, verbose_name='إجمالي الإشعارات')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='متوسط زمن الاستجابة')),
                ('system_uptime', models.FloatField(default=100.0, verbose_name='وقت تشغيل النظام')),
                ('error_rate', models.FloatField(default=0.0, verbose_name='معدل الأخطاء')),
                ('top_cities', models.JSONField(default=list, verbose_name='أهم المدن')),
                ('reports_by_gender', models.JSONField(default=dict, verbose_name='البلاغات حسب الجنس')),
                ('reports_by_age_group', models.JSONField(default=dict, verbose_name='البلاغات حسب الفئة العمرية')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الحساب')),
            ],
            options={
                'verbose_name': 'إحصائية يومية',
                'verbose_name_plural': 'الإحصائيات اليومية',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_db3351_idx')],
            },
        ),
    ]
