# Generated by Django 4.2 on 2026-01-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='طريقة الطلب')),
                ('path', models.CharField(max_length=500, verbose_name='المسار')),
                ('status_code', models.IntegerField(verbose_name='رمز الحالة')),
                ('processing_time', models.FloatField(verbose_name='وقت المعالجة')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='معاملات الاستعلام')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='معرف المستخدم')),
                ('response_size', models.IntegerField(default=0, verbose_name='حجم الرد')),
                ('slow_queries', models.JSONField(blank=True, default=list, verbose_name='الاستعلامات البطيئة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
            options={
                'verbose_name': 'سجل طلب',
                'verbose_name_plural': 'سجل الطلبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
