# Generated by Django 4.2 on 2026-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='avg_resolution_time',
            field=models.FloatField(default=0.0, verbose_name='متوسط زمن الحل (ساعات)'),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='resolved_this_month',
            field=models.IntegerField(default=0, verbose_name='محلولة هذا الشهر'),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='resolved_this_week',
            field=models.IntegerField(default=0, verbose_name='محلولة هذا الأسبوع'),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='resolved_today',
            field=models.IntegerField(default=0, verbose_name='محلولة اليوم'),
        ),
    ]
