# Generated by Django 4.2.11 on 2026-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dailystats_avg_resolution_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsreport',
            name='charts',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='الرسوم البيانية'),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='البيانات'),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='filters',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='الفلاتر'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='filters',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='الفلاتر'),
        ),
    ]
