# Generated by Django 4.2.11 on 2026-03-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('user', 'مستخدم عادي'), ('volunteer', 'متطوع'), ('admin', 'مشرف'), ('super_admin', 'مدير نظام')], default='user', max_length=20, verbose_name='دور المستخدم'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'غير محقق'), ('pending', 'قيد الانتظار'), ('verified', 'تم التحقق'), ('rejected', 'مرفوض')], default='unverified', max_length=20, verbose_name='حالة التحقق'),
        ),
    ]
