# Generated by Django 4.2 on 2026-01-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_user_id_7b1069_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_action__f4611c_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_74c8d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_user_ro_29a8b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_verific_bb6596_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='blocking_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الحظر'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المديرية'),
        ),
        migrations.AddField(
            model_name='user',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='محظور'),
        ),
        migrations.AddField(
            model_name='user',
            name='uzlah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='العزلة'),
        ),
    ]
