# Generated by Django 4.2 on 2026-01-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_auditlog_accounts_au_user_id_7b1069_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resolved_reports',
            field=models.IntegerField(default=0, verbose_name='البلاغات المحلولة'),
        ),
    ]
