# Generated by Django 5.2.10 on 2026-03-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_role_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=0.0, verbose_name='درجة الثقة'),
        ),
    ]
