# Generated by Django 5.2.10 on 2026-01-20 16:48

import accounts.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_resolved_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='آخر تغيير لكلمة المرور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='المصادقة الثنائية'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=accounts.fields.EncryptedCharField(blank=True, max_length=255, null=True, unique=True, verbose_name='رقم الهوية الوطنية'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=accounts.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
