# Generated by Django 5.2.10 on 2026-03-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_district_alter_user_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='رمز التحقق'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء رمز التحقق'),
        ),
    ]
