# Generated by Django 4.2.11 on 2026-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_otp_code_user_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='user',
            name='last_otp_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر طلب رمز'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.IntegerField(default=0, verbose_name='محاولات التحقق'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='رقم الهاتف موثق'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'مستخدم عادي'), ('volunteer', 'متطوع'), ('admin', 'مشرف'), ('super_admin', 'مدير نظام')], default='user', max_length=20, verbose_name='نوع المستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'غير محقق'), ('pending', 'قيد الانتظار'), ('verified', 'تم التحقق'), ('rejected', 'مرفوض')], default='unverified', max_length=20, verbose_name='حالة التحقق من الهوية'),
        ),
    ]
