# Generated by Django 4.2.11 on 2026-03-10 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_uzlah_options'),
        ('accounts', '0006_remove_user_is_staff_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uzlah',
        ),
        migrations.AddField(
            model_name='user',
            name='home_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='locations.district', verbose_name='مديرية السكن'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='locations.governorate', verbose_name='محافظة السكن'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_uzlah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='locations.uzlah', verbose_name='عزلة السكن'),
        ),
    ]
