# Generated by Django 5.2.10 on 2026-03-14 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_district_remove_user_governorate_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0003_alter_uzlah_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='يحدد ما إذا كان المستخدم يمكنه الدخول إلى لوحة الإدارة', verbose_name='موظف'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر نشاط'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='اللقب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, help_text='رقم الهاتف يجب أن يكون بصيغة: 777123456 أو +967777123456', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يتكون من 8 إلى 15 رقمًا، ويمكن أن يبدأ بـ +', regex='^\\+?[0-9]{8,15}$'), django.core.validators.MinLengthValidator(8)], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='رقم الهاتف موثق'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'مستخدم عادي'), ('volunteer', 'متطوع'), ('admin', 'مشرف'), ('super_admin', 'مدير نظام')], db_index=True, default='user', max_length=20, verbose_name='نوع المستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'غير محقق'), ('pending', 'قيد الانتظار'), ('verified', 'تم التحقق'), ('rejected', 'مرفوض')], db_index=True, default='unverified', max_length=20, verbose_name='حالة التحقق من الهوية'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone', 'is_active'], name='accounts_us_phone_bb152a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'verification_status'], name='accounts_us_user_ty_99c722_idx'),
        ),
    ]
