# Generated by Django 5.2.10 on 2026-01-16 18:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('priority_level', models.IntegerField(default=1, verbose_name='مستوى الأولوية')),
                ('response_time_hours', models.IntegerField(default=24, verbose_name='وقت الاستجابة المستهدف (ساعات)')),
                ('special_procedures', models.TextField(blank=True, verbose_name='إجراءات خاصة')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='GeographicalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('area_name', models.CharField(max_length=100, verbose_name='اسم المنطقة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض المركزي')),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول المركزي')),
                ('radius_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='نصف القطر (كم)')),
                ('boundary_coordinates', models.JSONField(blank=True, null=True, verbose_name='حدود المنطقة')),
                ('active_volunteers', models.IntegerField(default=0, verbose_name='المتطوعين النشطين')),
                ('active_reports', models.IntegerField(default=0, verbose_name='البلاغات النشطة')),
                ('coordinator_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المنسق')),
                ('coordinator_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف المنسق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منطقة جغرافية',
                'verbose_name_plural': 'المناطق الجغرافية',
                'unique_together': {('area_name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف البلاغ')),
                ('report_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='كود البلاغ')),
                ('report_type', models.CharField(choices=[('missing', 'شخص مفقود'), ('found', 'شخص تم العثور عليه')], default='missing', max_length=20, verbose_name='نوع البلاغ')),
                ('person_name', models.CharField(max_length=255, verbose_name='اسم الشخص')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='العمر')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى'), ('U', 'غير معروف')], default='U', max_length=1, verbose_name='الجنس')),
                ('nationality', models.CharField(blank=True, default='', max_length=100, verbose_name='الجنسية')),
                ('primary_photo', models.ImageField(blank=True, null=True, upload_to='reports/photos/', verbose_name='الصورة الرئيسية')),
                ('additional_photos', models.JSONField(blank=True, default=list, verbose_name='صور إضافية')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الطول (سم)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الوزن (كجم)')),
                ('body_build', models.CharField(blank=True, max_length=50, verbose_name='البنية الجسدية')),
                ('skin_color', models.CharField(blank=True, max_length=50, verbose_name='لون البشرة')),
                ('eye_color', models.CharField(blank=True, max_length=50, verbose_name='لون العينين')),
                ('hair_color', models.CharField(blank=True, max_length=50, verbose_name='لون الشعر')),
                ('hair_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الشعر')),
                ('distinctive_features', models.TextField(blank=True, verbose_name='ملامح مميزة')),
                ('scars_marks', models.TextField(blank=True, verbose_name='ندوب أو علامات')),
                ('tattoos', models.TextField(blank=True, verbose_name='الوشوم')),
                ('last_seen_location', models.CharField(max_length=500, verbose_name='آخر مكان رؤيته')),
                ('last_seen_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ آخر رؤية')),
                ('last_seen_time', models.TimeField(blank=True, null=True, verbose_name='وقت آخر رؤية')),
                ('missing_from', models.CharField(blank=True, max_length=255, verbose_name='مفقود من')),
                ('circumstances', models.TextField(blank=True, verbose_name='ظروف الفقدان')),
                ('found_location', models.CharField(blank=True, max_length=500, verbose_name='مكان العثور')),
                ('found_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العثور')),
                ('current_location', models.CharField(blank=True, max_length=500, verbose_name='المكان الحالي')),
                ('health_condition', models.TextField(blank=True, verbose_name='الحالة الصحية')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='اسم جهة الاتصال')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='هاتف الاتصال')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الاتصال')),
                ('contact_relationship', models.CharField(blank=True, max_length=100, verbose_name='صلة القرابة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('resolved', 'تم الحل'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة البلاغ')),
                ('requires_admin_review', models.BooleanField(default=False, verbose_name='يتطلب مراجعة مشرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='الحي/المنطقة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='نوع العملية')),
                ('action_details', models.TextField(verbose_name='تفاصيل العملية')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='البيانات القديمة')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='البيانات الجديدة')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='الحقول المتغيرة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='reports.report')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل تدقيق البلاغ',
                'verbose_name_plural': 'سجلات تدقيق البلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.category')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='reports.report')),
            ],
            options={
                'verbose_name': 'تصنيف البلاغ',
                'verbose_name_plural': 'تصنيفات البلاغات',
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/images/', verbose_name='الصورة')),
                ('face_embedding', models.JSONField(blank=True, null=True, verbose_name='بصمة الوجه')),
                ('embedding_version', models.CharField(blank=True, max_length=50, verbose_name='إصدار النموذج')),
                ('face_detected', models.BooleanField(default=False, verbose_name='تم اكتشاف الوجه')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='جودة الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('processing_status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتملة'), ('failed', 'فشلت')], default='pending', max_length=20, verbose_name='حالة المعالجة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report', verbose_name='البلاغ')),
            ],
            options={
                'verbose_name': 'صورة بلاغ',
                'verbose_name_plural': 'صور البلاغات',
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['person_name'], name='reports_rep_person__6fc0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['last_seen_date'], name='reports_rep_last_se_5e4971_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['city', 'district'], name='reports_rep_city_f66486_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'requires_admin_review'], name='reports_rep_status_0904ee_idx'),
        ),
        migrations.AddIndex(
            model_name='reportauditlog',
            index=models.Index(fields=['report', 'created_at'], name='reports_rep_report__04b96e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportauditlog',
            index=models.Index(fields=['action_type', 'created_at'], name='reports_rep_action__f9f7a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportcategory',
            unique_together={('report', 'category')},
        ),
    ]
