# Generated by Django 4.2.11 on 2026-03-10 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='معرف الشخص')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='الاسم الأول')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='الاسم الأوسط')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اللقب')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='العمر')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='الجنس')),
                ('health', models.CharField(blank=True, max_length=255, verbose_name='الحالة الصحية')),
                ('skin_color', models.CharField(blank=True, max_length=50, verbose_name='لون البشرة')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الطول (سم)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الوزن (كجم)')),
                ('eye_color', models.CharField(blank=True, max_length=50, verbose_name='لون العينين')),
                ('hair_color', models.CharField(blank=True, max_length=50, verbose_name='لون الشعر')),
                ('body_build', models.CharField(blank=True, max_length=50, verbose_name='البنية الجسدية')),
                ('description', models.TextField(blank=True, verbose_name='وصف تفصيلي')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'الأشخاص',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='معرف البلاغ')),
                ('report_code', models.CharField(max_length=50, unique=True, verbose_name='كود البلاغ')),
                ('report_type', models.CharField(max_length=50, verbose_name='نوع البلاغ')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('district', models.CharField(max_length=100, verbose_name='المديرية')),
                ('uzlah', models.CharField(max_length=100, verbose_name='العزلة')),
                ('last_seen_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ آخر مشاهدة')),
                ('last_seen_time', models.TimeField(blank=True, null=True, verbose_name='وقت آخر مشاهدة')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='حالة البلاغ')),
                ('importance', models.CharField(default='medium', max_length=50, verbose_name='مستوى الأهمية')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='هاتف الاتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.person', verbose_name='الشخص')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_path', models.ImageField(upload_to='reports/images/', verbose_name='الصورة')),
                ('face_embedding', models.JSONField(blank=True, null=True, verbose_name='بصمة الوجه')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='جودة الصورة')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report', verbose_name='البلاغ')),
            ],
        ),
    ]
