# Generated by Django 4.2 on 2026-01-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='close_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الإغلاق'),
        ),
        migrations.AddField(
            model_name='report',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
    ]
