# Generated by Django 5.2.10 on 2026-03-10 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.district', verbose_name='المديرية'),
        ),
        migrations.AddField(
            model_name='report',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.governorate', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='report',
            name='uzlah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.uzlah', verbose_name='العزلة'),
        ),
    ]
