# Generated by Django 4.2.11 on 2026-03-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_district_options_alter_governorate_options_and_more'),
        ('reports', '0002_alter_report_district_alter_report_governorate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'بلاغ', 'verbose_name_plural': 'البلاغات'},
        ),
        migrations.AlterModelOptions(
            name='reportimage',
            options={'ordering': ['-upload_at'], 'verbose_name': 'صورة البلاغ', 'verbose_name_plural': 'صور البلاغات'},
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='report',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.district', verbose_name='المديرية'),
        ),
        migrations.AlterField(
            model_name='report',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.governorate', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='report',
            name='importance',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', max_length=50, verbose_name='مستوى الأهمية'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('missing', 'مفقود'), ('found', 'معثور عليه')], max_length=50, verbose_name='نوع البلاغ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('resolved', 'تم الحل'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], default='pending', max_length=50, verbose_name='حالة البلاغ'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_path',
            field=models.ImageField(upload_to='reports/images/%Y/%m/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الرفع'),
        ),
    ]
