# Generated by Django 4.2 on 2026-01-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_close_reason_report_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='age_group',
            field=models.CharField(blank=True, choices=[('infant', 'رضيع'), ('child', 'طفل'), ('teen', 'مراهق'), ('adult', 'بالغ'), ('senior', 'مسن')], max_length=20, null=True, verbose_name='الفئة العمرية'),
        ),
        migrations.AddField(
            model_name='report',
            name='clothing_description',
            field=models.TextField(blank=True, default='', verbose_name='وصف الملابس'),
        ),
        migrations.AddField(
            model_name='report',
            name='importance_level',
            field=models.CharField(choices=[('high', 'مرتفع'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20, verbose_name='درجة الأهمية'),
        ),
    ]
