# Generated by Django 4.2.11 on 2026-03-10 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0003_alter_uzlah_options'),
        ('reports', '0003_alter_report_options_alter_reportimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='body_build',
        ),
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='person',
            name='health',
        ),
        migrations.RemoveField(
            model_name='person',
            name='height',
        ),
        migrations.RemoveField(
            model_name='person',
            name='skin_color',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='report',
            name='district',
        ),
        migrations.RemoveField(
            model_name='report',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='uzlah',
        ),
        migrations.AddField(
            model_name='person',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='فصيلة الدم'),
        ),
        migrations.AddField(
            model_name='person',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='مثل: سكري، ضغط، ربو', verbose_name='أمراض مزمنة'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='person',
            name='home_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.district', verbose_name='مديرية السكن'),
        ),
        migrations.AddField(
            model_name='person',
            name='home_governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.governorate', verbose_name='محافظة السكن'),
        ),
        migrations.AddField(
            model_name='person',
            name='home_uzlah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.uzlah', verbose_name='عزلة السكن'),
        ),
        migrations.AddField(
            model_name='person',
            name='permanent_marks',
            field=models.TextField(blank=True, help_text='ندوب، وشوم، علامات مميزة', verbose_name='علامات دائمة'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='report',
            name='close_reason',
            field=models.TextField(blank=True, verbose_name='سبب الإغلاق'),
        ),
        migrations.AddField(
            model_name='report',
            name='clothing_description',
            field=models.TextField(blank=True, verbose_name='وصف الملابس'),
        ),
        migrations.AddField(
            model_name='report',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, verbose_name='جهة الاتصال'),
        ),
        migrations.AddField(
            model_name='report',
            name='health_at_loss',
            field=models.CharField(max_length=255, null=True, verbose_name='الحالة الصحية وقت الفقدان/العثور'),
        ),
        migrations.AddField(
            model_name='report',
            name='lost_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='locations.district', verbose_name='مديرية الفقدان/العثور'),
        ),
        migrations.AddField(
            model_name='report',
            name='lost_governorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='locations.governorate', verbose_name='محافظة الفقدان/العثور'),
        ),
        migrations.AddField(
            model_name='report',
            name='lost_location_details',
            field=models.TextField(blank=True, verbose_name='تفاصيل الموقع'),
        ),
        migrations.AddField(
            model_name='report',
            name='lost_uzlah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='locations.uzlah', verbose_name='عزلة الفقدان/العثور'),
        ),
        migrations.AddField(
            model_name='report',
            name='medications',
            field=models.TextField(blank=True, verbose_name='أدوية يتناولها'),
        ),
        migrations.AddField(
            model_name='report',
            name='possessions',
            field=models.TextField(blank=True, verbose_name='ممتلكات معه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='اللقب'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاسم الأوسط'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='هاتف الاتصال'),
        ),
        migrations.AlterField(
            model_name='report',
            name='importance',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', max_length=10, verbose_name='مستوى الأهمية'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_seen_date',
            field=models.DateField(null=True, verbose_name='تاريخ آخر مشاهدة/عثور'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_seen_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت آخر مشاهدة/عثور'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('missing', 'مفقود'), ('found', 'معثور عليه')], max_length=10, verbose_name='نوع البلاغ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('resolved', 'تم الحل'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة البلاغ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='المبلغ'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name'], name='reports_per_first_n_8dce5b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['date_of_birth'], name='reports_per_date_of_e81982_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_code'], name='reports_rep_report__f1c62b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='reports_rep_status_22ec20_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['lost_governorate', 'lost_district'], name='reports_rep_lost_go_42906e_idx'),
        ),
    ]
