# Generated by Django 4.2 on 2026-01-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_age_group_report_clothing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_reports', to='reports.report', verbose_name='دمج في بلاغ'),
        ),
    ]
