# Generated by Django 4.2.11 on 2026-03-12 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_uzlah_options'),
        ('reports', '0004_remove_person_age_remove_person_body_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='body_build',
            field=models.CharField(blank=True, choices=[('slim', 'نحيف'), ('average', 'متوسط'), ('athletic', 'رياضي'), ('heavy', 'ممتلئ')], max_length=20, verbose_name='البنية الجسدية'),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف إضافي'),
        ),
        migrations.AddField(
            model_name='person',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('black', 'أسود'), ('brown', 'بني'), ('hazel', 'عسلي'), ('green', 'أخضر'), ('blue', 'أزرق'), ('grey', 'رمادي')], max_length=20, verbose_name='لون العينين'),
        ),
        migrations.AddField(
            model_name='person',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('black', 'أسود'), ('brown', 'بني'), ('blonde', 'أشقر'), ('red', 'أحمر'), ('white', 'أبيض'), ('grey', 'رمادي'), ('bald', 'أصلع')], max_length=20, verbose_name='لون الشعر'),
        ),
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='الطول (سم)'),
        ),
        migrations.AddField(
            model_name='person',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('light', 'فاتح'), ('fair', 'حنطي'), ('medium', 'متوسط'), ('olive', 'خمري'), ('brown', 'أسمر'), ('black', 'أسود')], max_length=20, verbose_name='لون البشرة'),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن (كجم)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإضافة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_phone',
            field=models.CharField(default='', max_length=20, verbose_name='هاتف الاتصال'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='health_at_loss',
            field=models.CharField(default='', max_length=255, verbose_name='الحالة الصحية وقت الفقدان/العثور'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='last_seen_date',
            field=models.DateField(default='2024-01-01', verbose_name='تاريخ آخر مشاهدة/عثور'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='lost_district',
            field=models.ForeignKey(default=83, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='locations.district', verbose_name='مديرية الفقدان/العثور'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='lost_governorate',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='locations.governorate', verbose_name='محافظة الفقدان/العثور'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الرفع'),
            preserve_default=False,
        ),
    ]
