# Generated by Django 5.2.10 on 2026-01-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_merged_into'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='للأطفال والنساء والحالات الخاصة', verbose_name='محتوى حساس'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مشاهدة'),
        ),
        migrations.AddField(
            model_name='report',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
    ]
