# Generated by Django 4.2.11 on 2026-02-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_is_sensitive_report_last_viewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='body_build',
            field=models.CharField(blank=True, choices=[('slim', 'نحيف'), ('average', 'متوسط'), ('athletic', 'رياضي'), ('heavy', 'ممتلئ')], max_length=50, verbose_name='البنية الجسدية'),
        ),
        migrations.AlterField(
            model_name='report',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('black', 'أسود'), ('brown', 'بني'), ('hazel', 'عسلي'), ('green', 'أخضر'), ('blue', 'أزرق'), ('grey', 'رمادي')], max_length=50, verbose_name='لون العينين'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('black', 'أسود'), ('brown', 'بني'), ('blonde', 'أشقر'), ('red', 'أحمر'), ('white', 'أبيض'), ('grey', 'رمادي'), ('bald', 'أصلع')], max_length=50, verbose_name='لون الشعر'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hair_type',
            field=models.CharField(blank=True, choices=[('straight', 'ناعم'), ('wavy', 'مموج'), ('curly', 'مجعد'), ('coily', 'خشن')], max_length=50, verbose_name='نوع الشعر'),
        ),
        migrations.AlterField(
            model_name='report',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('light', 'فاتح'), ('fair', 'حنطي'), ('medium', 'متوسط'), ('olive', 'خمري'), ('brown', 'أسمر'), ('black', 'أسود')], max_length=50, verbose_name='لون البشرة'),
        ),
    ]
