# Generated by Django 4.2.11 on 2026-03-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_person_body_build_person_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
    ]
