# Generated by Django 5.2.10 on 2026-03-14 01:04

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_uzlah_options'),
        ('reports', '0006_alter_person_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='body_build',
        ),
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='person',
            name='height',
        ),
        migrations.RemoveField(
            model_name='person',
            name='skin_color',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weight',
        ),
        migrations.AlterField(
            model_name='person',
            name='chronic_conditions',
            field=models.TextField(blank=True, verbose_name='أمراض مزمنة'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], db_index=True, max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='اللقب'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='الاسم الأوسط'),
        ),
        migrations.AlterField(
            model_name='person',
            name='permanent_marks',
            field=models.TextField(blank=True, verbose_name='علامات دائمة'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='هاتف الاتصال'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='report',
            name='health_at_loss',
            field=models.CharField(max_length=255, verbose_name='الحالة الصحية'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_seen_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ آخر مشاهدة/عثور'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='كود البلاغ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('missing', 'مفقود'), ('found', 'معثور عليه')], db_index=True, max_length=10, verbose_name='نوع البلاغ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('resolved', 'تم الحل'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=10, verbose_name='حالة البلاغ'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_path',
            field=models.ImageField(upload_to='reports/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='الصورة'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender'], name='reports_per_gender_9ac7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'report_type'], name='reports_rep_status_6f5566_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['last_seen_date'], name='reports_rep_last_se_5e4971_idx'),
        ),
        migrations.AddIndex(
            model_name='reportimage',
            index=models.Index(fields=['report', 'upload_at'], name='reports_rep_report__b6dad3_idx'),
        ),
    ]
