# Generated by Django 4.2.11 on 2026-03-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_person_body_build_remove_person_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_consent_given',
            field=models.BooleanField(default=False, verbose_name='تمت الموافقة على نشر الصور'),
        ),
    ]
