# Generated by Django 4.2.11 on 2026-03-14 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_image_consent_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_phone',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='هاتف الاتصال'),
        ),
    ]
