# Generated by Django 4.2.11 on 2026-03-12 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'إضافة'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('STATUS_CHANGE', 'تغيير حالة'), ('REVIEW', 'مراجعة')], max_length=20, verbose_name='العملية')),
                ('resource_type', models.CharField(max_length=100, verbose_name='نوع المورد')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='معرف المورد')),
                ('data_before', models.JSONField(blank=True, null=True, verbose_name='البيانات السابقة')),
                ('data_after', models.JSONField(blank=True, null=True, verbose_name='البيانات الجديدة')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ والوقت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل العمليات',
                'verbose_name_plural': 'سجلات العمليات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
