# Generated by Django 5.2.10 on 2026-01-16 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100, unique=True, verbose_name='اسم الإعداد')),
                ('similarity_threshold', models.FloatField(default=0.32, help_text='الحد الأدنى لدرجة التشابه للاعتبار كتطابق محتمل', verbose_name='عتبة التشابه الدنيا')),
                ('confidence_threshold', models.FloatField(default=70.0, help_text='الحد الأدنى لدرجة الثقة', verbose_name='عتبة الثقة الدنيا')),
                ('enable_face_matching', models.BooleanField(default=True, verbose_name='تفعيل مطابقة الوجوه')),
                ('enable_data_matching', models.BooleanField(default=True, verbose_name='تفعيل مطابقة البيانات')),
                ('enable_hybrid_matching', models.BooleanField(default=True, verbose_name='تفعيل المطابقة الهجينة')),
                ('face_weight', models.FloatField(default=0.7, verbose_name='وزن مطابقة الوجوه')),
                ('data_weight', models.FloatField(default=0.3, verbose_name='وزن مطابقة البيانات')),
                ('ai_model_version', models.CharField(default='MobileNetV2_v1.0', max_length=50, verbose_name='إصدار نموذج الذكاء الاصطناعي')),
                ('embedding_size', models.IntegerField(default=1280, verbose_name='حجم المتجه')),
                ('auto_match_enabled', models.BooleanField(default=True, verbose_name='التطابق التلقائي')),
                ('match_interval_hours', models.IntegerField(default=1, verbose_name='فترة التطابق (ساعات)')),
                ('notify_on_high_confidence', models.BooleanField(default=True, verbose_name='إشعار عند ثقة عالية')),
                ('notify_on_match', models.BooleanField(default=True, verbose_name='إشعار عند وجود تطابق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
            ],
            options={
                'verbose_name': 'إعداد المطابقة',
                'verbose_name_plural': 'إعدادات المطابقة',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف المطابقة')),
                ('similarity_score', models.FloatField(help_text='بين 0.0 و 1.0', verbose_name='درجة التشابه')),
                ('confidence_score', models.FloatField(help_text='بين 0 و 100', verbose_name='درجة الثقة')),
                ('confidence_level', models.CharField(choices=[('very_high', 'عالي جداً'), ('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20, verbose_name='مستوى الثقة')),
                ('match_type', models.CharField(choices=[('auto', 'تلقائي'), ('manual', 'يدوي'), ('admin', 'مشرف')], default='auto', max_length=20, verbose_name='نوع المطابقة')),
                ('match_status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewing', 'قيد التحقق'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('false_positive', 'إيجابي خاطئ')], default='pending', max_length=20, verbose_name='حالة المطابقة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('match_details', models.JSONField(blank=True, null=True, verbose_name='تفاصيل المطابقة')),
                ('matched_features', models.JSONField(blank=True, null=True, verbose_name='المميزات المتطابقة')),
                ('communication_opened', models.BooleanField(default=False, verbose_name='تم فتح التواصل')),
                ('communication_details', models.JSONField(blank=True, null=True, verbose_name='تفاصيل التواصل')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الكشف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('found_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_found', to='reports.report', verbose_name='بلاغ المعثور عليه')),
                ('missing_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_missing', to='reports.report', verbose_name='بلاغ المفقود')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'نتيجة مطابقة',
                'verbose_name_plural': 'نتائج المطابقة',
                'ordering': ['-similarity_score', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accept', 'قبول'), ('reject', 'رفض'), ('need_more_info', 'بحاجة لمزيد من المعلومات')], max_length=20, verbose_name='القرار')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('evidence_links', models.JSONField(blank=True, null=True, verbose_name='روابط الأدلة')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المراجعة')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='matching.matchresult')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مراجعة مطابقة',
                'verbose_name_plural': 'مراجعات المطابقة',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(verbose_name='متجه البصمة')),
                ('embedding_version', models.CharField(default='v1.0', max_length=50, verbose_name='إصدار النموذج')),
                ('face_count', models.IntegerField(default=0, verbose_name='عدد الوجوه المكتشفة')),
                ('face_analysis', models.JSONField(blank=True, null=True, verbose_name='تحليل الوجه')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='درجة الجودة')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='درجة الثقة')),
                ('processing_status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتملة'), ('failed', 'فشلت')], default='pending', max_length=20, verbose_name='حالة المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_embedding_obj', to='reports.reportimage', verbose_name='الصورة')),
            ],
            options={
                'verbose_name': 'بصمة وجه',
                'verbose_name_plural': 'بصمات الوجوه',
                'indexes': [models.Index(fields=['processing_status', 'created_at'], name='matching_fa_process_8dccfd_idx'), models.Index(fields=['quality_score'], name='matching_fa_quality_597792_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('MATCH_START', 'بدء عملية مطابقة'), ('MATCH_COMPLETE', 'اكتمال عملية مطابقة'), ('MATCH_FOUND', 'اكتشاف تطابق'), ('REVIEW_ACCEPT', 'قبول مراجعة'), ('REVIEW_REJECT', 'رفض مراجعة'), ('CONFIG_UPDATE', 'تحديث إعدادات')], max_length=50, verbose_name='نوع العملية')),
                ('action_details', models.TextField(verbose_name='تفاصيل العملية')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='زمن المعالجة (ثواني)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق المطابقة',
                'verbose_name_plural': 'سجلات تدقيق المطابقة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='matching_ma_action__5a8a50_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['missing_report', 'found_report'], name='matching_ma_missing_db32fe_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['similarity_score'], name='matching_ma_similar_ef738e_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['match_status', 'confidence_level'], name='matching_ma_match_s_252e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['detected_at'], name='matching_ma_detecte_b3041c_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchresult',
            constraint=models.UniqueConstraint(fields=('missing_report', 'found_report'), name='unique_match_pair'),
        ),
        migrations.AddConstraint(
            model_name='matchresult',
            constraint=models.CheckConstraint(check=models.Q(('similarity_score__gte', 0), ('similarity_score__lte', 1)), name='similarity_score_range'),
        ),
        migrations.AddConstraint(
            model_name='matchresult',
            constraint=models.CheckConstraint(check=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), name='confidence_score_range'),
        ),
    ]
