# Generated by Django 4.2.11 on 2026-03-10 03:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='معرف المطابقة')),
                ('similarity_score', models.FloatField(verbose_name='نسبة التشابه')),
                ('confidence_level', models.CharField(max_length=50, verbose_name='مستوى الثقة')),
                ('match_type', models.CharField(max_length=50, verbose_name='نوع المطابقة')),
                ('match_status', models.CharField(max_length=50, verbose_name='حالة المطابقة')),
                ('match_reason', models.TextField(blank=True, verbose_name='سبب المطابقة')),
                ('detect_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاكتشاف')),
                ('report_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_report_1', to='reports.report', verbose_name='البلاغ الأول')),
                ('report_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_report_2', to='reports.report', verbose_name='البلاغ الثاني')),
            ],
            options={
                'verbose_name': 'نتيجة مطابقة',
                'verbose_name_plural': 'نتائج المطابقة',
            },
        ),
    ]
