# Generated by Django 4.2 on 2026-01-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='is_experimental',
            field=models.BooleanField(default=False, verbose_name='تجريبي'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='priority_level',
            field=models.CharField(choices=[('urgent', 'عاجل (طفل/مسن)'), ('high', 'مرتفع'), ('normal', 'عادي')], default='normal', max_length=20, verbose_name='مستوى الأولوية'),
        ),
    ]
