# Generated by Django 5.2.10 on 2026-03-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100, verbose_name='نوع الإجراء')),
                ('report_count', models.IntegerField(default=0, verbose_name='عدد البلاغات')),
                ('processing_time', models.FloatField(verbose_name='وقت المعالجة (ثواني)')),
                ('status', models.CharField(max_length=50, verbose_name='الحالة')),
                ('message', models.TextField(blank=True, verbose_name='الرسالة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التنفيذ')),
            ],
            options={
                'verbose_name': 'سجل تدقيق مطابقة',
                'verbose_name_plural': 'سجل تدقيق المطابقات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
