# Generated by Django 4.2.11 on 2026-03-10 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_options_alter_reportimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0002_matchingauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ['-similarity_score', '-detected_at'], 'verbose_name': 'نتيجة مطابقة', 'verbose_name_plural': 'نتائج المطابقة'},
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='detect_at',
        ),
        migrations.AddField(
            model_name='matchingauditlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الاكتشاف'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='match_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='تفاصيل المطابقة'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='priority_level',
            field=models.CharField(choices=[('urgent', 'عاجل'), ('high', 'مرتفع'), ('normal', 'عادي'), ('low', 'منخفض')], default='normal', max_length=20, verbose_name='مستوى الأولوية'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المراجعة'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='matchingauditlog',
            name='action_type',
            field=models.CharField(choices=[('batch_match', 'مطابقة مجمعة'), ('single_match', 'مطابقة فردية'), ('review', 'مراجعة'), ('reprocess', 'إعادة معالجة')], max_length=50, verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='matchingauditlog',
            name='processing_time',
            field=models.FloatField(default=0.0, verbose_name='وقت المعالجة (ثواني)'),
        ),
        migrations.AlterField(
            model_name='matchingauditlog',
            name='status',
            field=models.CharField(default='success', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='matchingauditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت التنفيذ'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='confidence_level',
            field=models.CharField(choices=[('very_high', 'عالية جداً'), ('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=20, verbose_name='مستوى الثقة'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='match_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('false_positive', 'إيجابي خاطئ'), ('reviewing', 'قيد المراجعة اليدوية')], default='pending', max_length=20, verbose_name='حالة المطابقة'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='match_type',
            field=models.CharField(choices=[('auto', 'تلقائي'), ('manual', 'يدوي')], default='auto', max_length=20, verbose_name='نوع المطابقة'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='report_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_first', to='reports.report', verbose_name='البلاغ الأول'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='report_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_second', to='reports.report', verbose_name='البلاغ الثاني'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='similarity_score',
            field=models.FloatField(default=0.0, verbose_name='نسبة التشابه'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['match_status'], name='matching_ma_match_s_6c5f75_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['priority_level'], name='matching_ma_priorit_1d97e8_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['detected_at'], name='matching_ma_detecte_b3041c_idx'),
        ),
    ]
