# Generated by Django 5.2.10 on 2026-01-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matchresult_is_experimental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='human_reviewed',
            field=models.BooleanField(default=False, verbose_name='تمت المراجعة البشرية'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='match_algorithm',
            field=models.CharField(default='v1.0', max_length=50, verbose_name='خوارزمية المطابقة'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='match_confidence_breakdown',
            field=models.JSONField(blank=True, null=True, verbose_name='تفاصيل درجة الثقة'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='review_evidence',
            field=models.JSONField(blank=True, null=True, verbose_name='أدلة المراجعة'),
        ),
    ]
