# Generated by Django 4.2.11 on 2026-03-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_matchresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingauditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت التنفيذ'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاكتشاف'),
        ),
    ]
