# Generated by Django 5.2.10 on 2026-03-14 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_alter_matchingauditlog_timestamp_and_more'),
        ('reports', '0007_remove_person_body_build_remove_person_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=True, verbose_name='المطابقة صحيحة؟')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='التقييم')),
                ('comments', models.TextField(blank=True, verbose_name='تعليقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
            ],
            options={
                'verbose_name': 'تقييم مطابقة',
                'verbose_name_plural': 'تقييمات المطابقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ['-similarity_score', '-detected_at'], 'verbose_name': 'نتيجة مطابقة', 'verbose_name_plural': 'نتائج المطابقات'},
        ),
        migrations.AddField(
            model_name='matchresult',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together={('report_1', 'report_2')},
        ),
        migrations.AddIndex(
            model_name='matchingauditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='matching_ma_action__40bb45_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingauditlog',
            index=models.Index(fields=['status'], name='matching_ma_status_9db278_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['report_1', 'report_2'], name='matching_ma_report__da16e2_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['confidence_level', 'similarity_score'], name='matching_ma_confide_cfd7cf_idx'),
        ),
        migrations.AddField(
            model_name='matchfeedback',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matching.matchresult', verbose_name='المطابقة'),
        ),
        migrations.AddField(
            model_name='matchfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterUniqueTogether(
            name='matchfeedback',
            unique_together={('match', 'user')},
        ),
    ]
