# Generated by Django 5.2.10 on 2026-03-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المحافظة')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='رمز المحافظة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المديرية')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مديرية',
                'verbose_name_plural': 'المديريات',
                'ordering': ['governorate', 'name'],
                'unique_together': {('governorate', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Uzlah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العزلة')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzlahs', to='locations.district', verbose_name='المديرية')),
            ],
            options={
                'verbose_name': 'عزلة',
                'verbose_name_plural': 'العزل',
                'ordering': ['district', 'name'],
                'unique_together': {('district', 'name')},
            },
        ),
    ]
