# Generated by Django 4.2.11 on 2026-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['governorate__order', 'order', 'name'], 'verbose_name': 'مديرية', 'verbose_name_plural': 'المديريات'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'ordering': ['order', 'name'], 'verbose_name': 'محافظة', 'verbose_name_plural': 'المحافظات'},
        ),
        migrations.AlterModelOptions(
            name='uzlah',
            options={'ordering': ['district__governorate__order', 'district__order', 'order', 'name'], 'verbose_name': 'عزلة', 'verbose_name_plural': 'العزل'},
        ),
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='كود المديرية'),
        ),
        migrations.AddField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='district',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالعربية'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='district',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='district',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد السكان'),
        ),
        migrations.AddField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='المساحة (كم²)'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالعربية'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد السكان'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='uzlah',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='كود العزلة'),
        ),
        migrations.AddField(
            model_name='uzlah',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='uzlah',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='uzlah',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالعربية'),
        ),
        migrations.AddField(
            model_name='uzlah',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='uzlah',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='uzlah',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد السكان'),
        ),
        migrations.AddField(
            model_name='uzlah',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='كود المحافظة'),
        ),
    ]
