# Generated by Django 4.2.11 on 2026-03-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_district_options_alter_governorate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzlah',
            options={'ordering': ['district__order', 'order', 'name'], 'verbose_name': 'عزلة', 'verbose_name_plural': 'العزل'},
        ),
    ]
