# Generated by Django 5.2.10 on 2026-03-14 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_uzlah_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='population',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد السكان'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='المساحة يجب أن تكون 0 أو أكثر')], verbose_name='المساحة (كم²)'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='الكود يجب أن يكون من 2-10 أحرف كبيرة وأرقام فقط', regex='^[A-Z0-9]{2,10}$')], verbose_name='كود المحافظة'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='population',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='عدد السكان يجب أن يكون 0 أو أكثر')], verbose_name='عدد السكان'),
        ),
        migrations.AlterField(
            model_name='uzlah',
            name='population',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد السكان'),
        ),
    ]
