# Generated by Django 5.2.10 on 2026-01-16 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True, verbose_name='اسم القالب')),
                ('notification_type', models.CharField(choices=[('match_found', 'تم العثور على تطابق'), ('report_status_change', 'تغيير حالة البلاغ'), ('report_reviewed', 'تمت مراجعة البلاغ'), ('message_from_admin', 'رسالة من المشرف'), ('verification_status', 'حالة التحقق'), ('system_update', 'تحديث النظام'), ('volunteer_assignment', 'مهمة تطوعية'), ('urgent_alert', 'تنبيه عاجل')], max_length=50, verbose_name='نوع الإشعار')),
                ('title_ar', models.CharField(max_length=255, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='العنوان (إنجليزي)')),
                ('message_ar', models.TextField(verbose_name='النص (عربي)')),
                ('message_en', models.TextField(blank=True, verbose_name='النص (إنجليزي)')),
                ('variables', models.JSONField(default=list, help_text='قائمة المتغيرات المستخدمة في القالب، مثال: {user_name}, {report_code}', verbose_name='المتغيرات')),
                ('default_action_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء الافتراضي')),
                ('default_action_text_ar', models.CharField(blank=True, max_length=100, verbose_name='نص الإجراء (عربي)')),
                ('default_action_text_en', models.CharField(blank=True, max_length=100, verbose_name='نص الإجراء (إنجليزي)')),
                ('default_priority', models.CharField(choices=[('urgent', 'عاجل'), ('high', 'مهم'), ('normal', 'عادي'), ('low', 'منخفض')], default='normal', max_length=20, verbose_name='الأولوية الافتراضية')),
                ('default_expiry_days', models.IntegerField(default=7, verbose_name='صلاحية الإشعار (أيام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب إشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_match_notifications', models.BooleanField(default=True, verbose_name='إشعارات التطابق')),
                ('enable_report_updates', models.BooleanField(default=True, verbose_name='تحديثات البلاغات')),
                ('enable_admin_messages', models.BooleanField(default=True, verbose_name='رسائل المشرفين')),
                ('enable_system_updates', models.BooleanField(default=True, verbose_name='تحديثات النظام')),
                ('enable_urgent_alerts', models.BooleanField(default=True, verbose_name='تنبيهات عاجلة')),
                ('enable_volunteer_alerts', models.BooleanField(default=False, verbose_name='تنبيهات المتطوعين')),
                ('receive_push_notifications', models.BooleanField(default=True, verbose_name='الإشعارات الدفعية')),
                ('receive_email_notifications', models.BooleanField(default=True, verbose_name='الإشعارات بالبريد')),
                ('receive_sms_notifications', models.BooleanField(default=False, verbose_name='الإشعارات بالرسائل')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='بداية ساعات الهدوء')),
                ('quiet_hours_end', models.TimeField(default='07:00', verbose_name='نهاية ساعات الهدوء')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='تفعيل ساعات الهدوء')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'الإنجليزية')], default='ar', max_length=10, verbose_name='اللغة المفضلة')),
                ('app_update_frequency', models.CharField(choices=[('immediate', 'فوري'), ('daily', 'يومي'), ('weekly', 'أسبوعي')], default='daily', max_length=20, verbose_name='تكرار تحديث التطبيق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تفضيل الإشعار',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف الإشعار')),
                ('notification_type', models.CharField(choices=[('match_found', 'تم العثور على تطابق'), ('report_status_change', 'تغيير حالة البلاغ'), ('report_reviewed', 'تمت مراجعة البلاغ'), ('message_from_admin', 'رسالة من المشرف'), ('verification_status', 'حالة التحقق'), ('system_update', 'تحديث النظام'), ('volunteer_assignment', 'مهمة تطوعية'), ('urgent_alert', 'تنبيه عاجل')], default='system_update', max_length=50, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('priority_level', models.CharField(choices=[('urgent', 'عاجل'), ('high', 'مهم'), ('normal', 'عادي'), ('low', 'منخفض')], default='normal', max_length=20, verbose_name='مستوى الأولوية')),
                ('action_required', models.BooleanField(default=False, verbose_name='يتطلب إجراء')),
                ('action_url', models.URLField(blank=True, verbose_name='رابط الإجراء')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='نص الإجراء')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('delivery_method', models.JSONField(default=list, help_text='قائمة بطرق التوصيل المستخدمة: [push, email, sms, in_app]', verbose_name='طريقة التوصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('related_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='matching.matchresult', verbose_name='المطابقة المرتبطة')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reports.report', verbose_name='البلاغ المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'), models.Index(fields=['priority_level', 'created_at'], name='notificatio_priorit_acc240_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True, verbose_name='رمز الجهاز')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20, verbose_name='نوع الجهاز')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الجهاز')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='موديل الجهاز')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='إصدار التطبيق')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='إصدار النظام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رمز إشعار دفعي',
                'verbose_name_plural': 'رموز الإشعارات الدفعية',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_4af7b0_idx'), models.Index(fields=['device_type', 'is_active'], name='notificatio_device__fc4313_idx')],
            },
        ),
    ]
