# Generated by Django 4.2.11 on 2026-03-10 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_options_alter_reportimage_options_and_more'),
        ('matching', '0003_alter_matchresult_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='report_1',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='report_2',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_required',
            field=models.BooleanField(default=False, verbose_name='يتطلب إجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='نص الزر'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='matching.matchresult'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('match_found', 'تم العثور على تطابق'), ('report_status_change', 'تغيير حالة البلاغ'), ('verification_status', 'تغيير حالة التحقق'), ('urgent_alert', 'تنبيه عاجل'), ('system_update', 'تحديث النظام'), ('message_from_admin', 'رسالة من المشرف')], max_length=50, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority_level',
            field=models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='مستوى الأولوية'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستهدف'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
    ]
