# Generated by Django 5.2.10 on 2026-03-14 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_report_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='البريد الإلكتروني')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='الرسائل النصية')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='الإشعارات الدفعية')),
                ('notify_match_found', models.BooleanField(default=True, verbose_name='اكتشاف تطابق')),
                ('notify_report_status', models.BooleanField(default=True, verbose_name='تغيير حالة البلاغ')),
                ('notify_verification', models.BooleanField(default=True, verbose_name='حالة التحقق')),
                ('notify_system', models.BooleanField(default=True, verbose_name='تحديثات النظام')),
                ('notify_admin', models.BooleanField(default=True, verbose_name='رسائل المشرفين')),
                ('min_priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الحد الأدنى للأولوية')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='بدء وقت الهدوء')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية وقت الهدوء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
    ]
